// Auto-generated — do not edit by hand.
export interface Airport {
  code: string; // 3-letter IATA code
  name: string;
}

export const US_AIRPORTS: Airport[] = [
  { code: 'ABE', name: 'Allentown' },
  { code: 'ABQ', name: 'Albuquerque International Airport' },
  { code: 'ACK', name: 'Nantucket' },
  { code: 'ACY', name: 'Atlantic City International Airport' },
  { code: 'AGS', name: 'Augusta' },
  { code: 'ALB', name: 'Albany International Airport' },
  { code: 'ALM', name: 'Alamogordo' },
  { code: 'AMA', name: 'Amarillo' },
  { code: 'ANC', name: 'Anchorage International Airport' },
  { code: 'ASE', name: 'Aspen' },
  { code: 'ATL', name: 'Atlanta Hartsfield International Airport' },
  { code: 'AUG', name: 'Augusta' },
  { code: 'AUS', name: 'Austin Bergstrom International Airport' },
  { code: 'AVL', name: 'Asheville' },
  { code: 'AVP', name: 'Scranton' },
  { code: 'AZO', name: 'Kalamazoo-Battle Creek International Airport' },
  { code: 'BDL', name: 'Hartford' },
  { code: 'BGR', name: 'Bangor' },
  { code: 'BHM', name: 'Birmingham International Airport' },
  { code: 'BIL', name: 'Billings' },
  { code: 'BIS', name: 'Bismark' },
  { code: 'BNA', name: 'Nashville' },
  { code: 'BOI', name: 'Boise' },
  { code: 'BOS', name: 'Boston, Logan International Airport' },
  { code: 'BTL', name: 'Battlecreek' },
  { code: 'BTR', name: 'Baton Rouge' },
  { code: 'BTV', name: 'Burlington' },
  { code: 'BUF', name: 'Buffalo' },
  { code: 'BUR', name: 'Burbank' },
  { code: 'BWI', name: 'Baltimore' },
  { code: 'CAE', name: 'Columbia' },
  { code: 'CAK', name: 'Akron' },
  { code: 'CHA', name: 'Chattanooga' },
  { code: 'CHS', name: 'Charleston' },
  { code: 'CID', name: 'Cedar Rapids' },
  { code: 'CKB', name: 'Clarksburg' },
  { code: 'CLE', name: 'Cleveland' },
  { code: 'CLT', name: 'Charlotte/Douglas International Airport' },
  { code: 'CMH', name: 'Columbus' },
  { code: 'COS', name: 'Colorado Springs' },
  { code: 'CPR', name: 'Casper' },
  { code: 'CRP', name: 'Corpus Christi' },
  { code: 'CRW', name: 'Charleston' },
  { code: 'CVG', name: 'Cincinnati' },
  { code: 'CYS', name: 'Cheyenne' },
  { code: 'DAB', name: 'Daytona Beach' },
  { code: 'DAL', name: 'Dallas Love Field Airport' },
  { code: 'DAY', name: 'Dayton' },
  { code: 'DCA', name: 'Washington National Airport' },
  { code: 'DEN', name: 'Denver International Airport' },
  { code: 'DET', name: 'Detroit' },
  { code: 'DFW', name: 'Dallas/Fort Worth International Airport' },
  { code: 'DHN', name: 'Dothan Regional Airport' },
  { code: 'DLH', name: 'Duluth' },
  { code: 'DSM', name: 'Des Moines' },
  { code: 'DTW', name: 'Detroit Metropolitan Airport' },
  { code: 'ELP', name: 'El Paso' },
  { code: 'ERI', name: 'Erie' },
  { code: 'EUG', name: 'Eugene' },
  { code: 'EVV', name: 'Evansville' },
  { code: 'EWR', name: 'Newark International Airport' },
  { code: 'EYW', name: 'Key West International Airport' },
  { code: 'FAI', name: 'Fairbanks International Airport' },
  { code: 'FAR', name: 'Fargo' },
  { code: 'FAT', name: 'Fresno' },
  { code: 'FAY', name: 'Fayetteville' },
  { code: 'FLG', name: 'Flagstaff' },
  { code: 'FLL', name: 'Fort Lauderdale-Hollywood International Airport' },
  { code: 'FNT', name: 'Flint' },
  { code: 'FSD', name: 'Sioux Falls' },
  { code: 'FWA', name: 'Fort Wayne' },
  { code: 'FYV', name: 'Fayetteville' },
  { code: 'GEG', name: 'Spokane International Airport' },
  { code: 'GJT', name: 'Grand Junction' },
  { code: 'GPT', name: 'Gulfport' },
  { code: 'GRB', name: 'Green Bay' },
  { code: 'GRR', name: 'Grand Rapids' },
  { code: 'GSO', name: 'Greensboro' },
  { code: 'GSP', name: 'Greenville' },
  { code: 'HIO', name: 'Portland, Hillsboro Airport' },
  { code: 'HNL', name: 'Honolulu International Airport' },
  { code: 'HOU', name: 'Houston, William B Hobby Airport' },
  { code: 'HPN', name: 'Westchester' },
  { code: 'HSV', name: 'Huntsville International Airport' },
  { code: 'HTS', name: 'Huntington Tri-State Airport' },
  { code: 'HVN', name: 'Tweed New Haven' },
  { code: 'HYA', name: 'Hyannis' },
  { code: 'IAD', name: 'Washington, Dulles International Airport' },
  { code: 'IAH', name: 'Houston, George Bush Intercontinental Airport' },
  { code: 'ICT', name: 'Wichita' },
  { code: 'IND', name: 'Indianapolis International Airport' },
  { code: 'INT', name: 'Winston-Salem' },
  { code: 'ISP', name: 'Islip' },
  { code: 'ITO', name: 'Hilo' },
  { code: 'JAC', name: 'Jackson Hole' },
  { code: 'JAN', name: 'Jackson' },
  { code: 'JAX', name: 'Jacksonville' },
  { code: 'JFK', name: 'New York, John F Kennedy International Airport' },
  { code: 'JNU', name: 'Juneau International Airport' },
  { code: 'KOA', name: 'Kailua' },
  { code: 'LAN', name: 'Lansing' },
  { code: 'LAS', name: 'Las Vegas, Las Vegas McCarran International Airport' },
  { code: 'LAX', name: 'Los Angeles International Airport' },
  { code: 'LBB', name: 'Lubbock' },
  { code: 'LEX', name: 'Lexington' },
  { code: 'LGA', name: 'New York, La Guardia Airport' },
  { code: 'LGB', name: 'Long Beach' },
  { code: 'LIH', name: 'Lihue' },
  { code: 'LIT', name: 'Little Rock National Airport' },
  { code: 'LNK', name: 'Lincoln' },
  { code: 'MAF', name: 'Midland' },
  { code: 'MBS', name: 'Saginaw' },
  { code: 'MCI', name: 'Kansas City' },
  { code: 'MCO', name: 'Orlando' },
  { code: 'MDT', name: 'Harrisburg' },
  { code: 'MDW', name: 'Chicago Midway Airport' },
  { code: 'MEM', name: 'Memphis' },
  { code: 'MGM', name: 'Montgomery' },
  { code: 'MHT', name: 'Manchester' },
  { code: 'MIA', name: 'Miami International Airport' },
  { code: 'MKE', name: 'Milwaukee' },
  { code: 'MLI', name: 'Moline' },
  { code: 'MOB', name: 'Mobile' },
  { code: 'MPV', name: 'Montpelier' },
  { code: 'MSN', name: 'Madison' },
  { code: 'MSP', name: 'Minneapolis/St.Paul International Airport' },
  { code: 'MSY', name: 'New Orleans International Airport' },
  { code: 'MYR', name: 'Myrtle Beach' },
  { code: 'OAK', name: 'Oakland' },
  { code: 'OGG', name: 'Kahului' },
  { code: 'OKC', name: 'Oklahoma City' },
  { code: 'OMA', name: 'Omaha' },
  { code: 'ONT', name: 'Ontario' },
  { code: 'ORD', name: 'Chicago, O\'Hare International Airport Airport' },
  { code: 'ORF', name: 'Norfolk' },
  { code: 'ORH', name: 'Worcester' },
  { code: 'PBI', name: 'West Palm Beach' },
  { code: 'PDX', name: 'Portland International Airport' },
  { code: 'PFN', name: 'Panama City-Bay County International Airport' },
  { code: 'PHF', name: 'Newport News' },
  { code: 'PHL', name: 'Philadelphia' },
  { code: 'PHX', name: 'Phoenix, Phoenix Sky Harbor International Airport' },
  { code: 'PIA', name: 'Peoria' },
  { code: 'PIE', name: 'St. Petersburg' },
  { code: 'PIR', name: 'Pierre' },
  { code: 'PIT', name: 'Pittsburgh' },
  { code: 'PNS', name: 'Pensacola' },
  { code: 'PSC', name: 'Pasco, Pasco/Tri-Cities Airport' },
  { code: 'PSP', name: 'Palm Springs' },
  { code: 'PUB', name: 'Pueblo' },
  { code: 'PVD', name: 'Providence - T.F. Green Airport' },
  { code: 'PVU', name: 'Provo Municipal Airport' },
  { code: 'PWM', name: 'Portland' },
  { code: 'RAP', name: 'Rapid City' },
  { code: 'RDU', name: 'Raleigh' },
  { code: 'RIC', name: 'Richmond' },
  { code: 'RKS', name: 'Rock Springs' },
  { code: 'RNO', name: 'Reno-Tahoe International Airport' },
  { code: 'ROA', name: 'Roanoke' },
  { code: 'ROC', name: 'Rochester' },
  { code: 'RST', name: 'Rochester' },
  { code: 'RSW', name: 'Fort Meyers' },
  { code: 'RUT', name: 'Rutland' },
  { code: 'SAN', name: 'San Diego' },
  { code: 'SAT', name: 'San Antonio International Airport' },
  { code: 'SAV', name: 'Savannah' },
  { code: 'SBN', name: 'South Bend' },
  { code: 'SDF', name: 'Louisville' },
  { code: 'SEA', name: 'Seattle, Tacoma International Airport' },
  { code: 'SFO', name: 'San Francisco International Airport' },
  { code: 'SGF', name: 'Springfield' },
  { code: 'SHV', name: 'Shreveport' },
  { code: 'SJC', name: 'San Jose' },
  { code: 'SLC', name: 'Salt Lake City' },
  { code: 'SLE', name: 'Salem' },
  { code: 'SMF', name: 'Sacramento' },
  { code: 'SNA', name: 'Santa Ana' },
  { code: 'SRQ', name: 'Sarasota' },
  { code: 'STL', name: 'St Louis, Lambert International Airport' },
  { code: 'SWF', name: 'Newburgh' },
  { code: 'SYR', name: 'Syracuse' },
  { code: 'TOL', name: 'Toledo' },
  { code: 'TPA', name: 'Tampa' },
  { code: 'TRI', name: 'Bristol' },
  { code: 'TTN', name: 'Trenton' },
  { code: 'TUL', name: 'Tulsa' },
  { code: 'TUS', name: 'Tucson International Airport' },
  { code: 'TYS', name: 'Knoxville' },
  { code: 'XNA', name: 'Northwest Arkansas Regional Airport' },
  { code: 'YUM', name: 'Yuma International Airport' },
];
